[workspace]
resolver = "2"

members = [
    "crates/ryg-rans-rs-core",
    "crates/ryg-rans-rs-simd",
    "crates/ryg-rans-rs",
    "crates/ryg-rans-rs-oracle",
    "crates/ryg-rans-rs-casefile",
    "crates/ryg-rans-rs-cli",
    "crates/ryg-rans-rs-parallel",
    "crates/ryg-rans-rs-bench",
    "xtask",
]

[workspace.dependencies]
criterion = { version = "0.5", default-features = false, features = ["cargo_bench_support"] }
ryg-rans-rs-core = { version = "0.4.1", path = "crates/ryg-rans-rs-core" }
ryg-rans-rs-simd = { version = "0.4.1", path = "crates/ryg-rans-rs-simd" }
ryg-rans-rs-parallel = { version = "0.4.1", path = "crates/ryg-rans-rs-parallel" }

[workspace.package]
repository = "https://github.com/infinityabundance/ryg-rans-rs"
license = "MIT OR Apache-2.0"
edition = "2024"
