[package]
name = "ryg-rans-rs-simd"
version = "0.1.21"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "SSE4.1 accelerated rANS decoder kernels"

[features]
default = []
std = []

[dependencies]
ryg-rans-rs-core = { version = "0.1.21", path = "../ryg-rans-rs-core" }
